# 指定运行环境
language: node_js

node_js:
  - lts/*

branches:
  only:
  - develop

jobs:
  include:
    - name: "Push Compile"
      if: type = push
      install: yarn install
      before_script:
        - rm -rf dist
      script:
        - npm run build
      after_success:
        - git config --global user.name "murong"
        - git config --global user.email "372638156@qq.com"
        - git add -A
        - "git commit -m 'build: Travis CI automatic compilation'"
        - git pull --rebase
        - git push "https://murongg:${GITHUB_TOKEN}@github.com/vue3-lazyload" HEAD:develop
